version: '3.8'
services:
  # Django App
  reinodamata_backend:
   container_name: django
   build: .
   volumes:
    - .:/app
   ports:
    - 8000:8000
   depends_on:
    - reinodamata_db
    - reinodamata_redis
   
  # Database (PostgreSQL)
  reinodamata_db:
   image: postgres
   container_name: postgresql
   restart: always
   environment:
      POSTGRES_DB: reinodamata_db
      POSTGRES_USER: reinodamata
      POSTGRES_PASSWORD: postgres
   ports:
    - 5432:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  reinodamata_redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379